### ISSUE TITLE
TypeError: expected input to be a string or buffer

### ISSUE THREAD

**Issue by JFossey** [thetre97/gridsome-transformer-image#1]
I am currently investigating different image handling solutions with gridsome and tried to use this plugin and got the following build error.

```
Initializing plugins...
TypeError: expected input to be a string or buffer
    at Object.exports.toString (/var/www/test/local-images/node_modules/gray-matter/lib/utils.js:46:11)
    at module.exports (/var/www/test/local-images/node_modules/gray-matter/lib/to-file.js:39:24)
    at matter (/var/www/test/local-images/node_modules/gray-matter/index.js:34:14)
    at RemarkTransformer.parse (/var/www/test/local-images/node_modules/@gridsome/transformer-remark/index.js:47:40)
    at transformNodeContent (/var/www/test/local-images/node_modules/gridsome/lib/store/transformNodeContent.js:21:43)
    at SyncBailWaterfallHook.eval [as call] (eval at create (/var/www/test/local-images/node_modules/gridsome/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:115:17)
    at SyncBailWaterfallHook.lazyCompileHook (/var/www/test/local-images/node_modules/gridsome/node_modules/tapable/lib/Hook.js:156:20)
    at Collection.addNode (/var/www/test/local-images/node_modules/gridsome/lib/store/Collection.js:72:50)
    at /var/www/test/local-images/node_modules/@gridsome/source-filesystem/index.js:67:36
    at async Promise.all (index 0)
    at async FilesystemSource.createNodes (/var/www/test/local-images/node_modules/@gridsome/source-filesystem/index.js:65:5)
    at async /var/www/test/local-images/node_modules/@gridsome/source-filesystem/index.js:33:7
    at async Plugins.run (/var/www/test/local-images/node_modules/gridsome/lib/app/Plugins.js:141:11)

```

When I comment out the plugins constructor the build error goes away.

I am using remark markdown with gridsome v0.7.23.

**Comment by travis-r6s** [comment]
Hey @JFossey - would you be able to share your `gridsome.config.js` please?

**Comment by JFossey** [comment]
Hi @thetre97 

I dont know if it helps but, I got this error building without out updating my config, just by installing the package my build broke.

Then I copied the example you provide to see if it makes a difference and it caused the same error.

After messing around a little I found only 2 things got the build to work without this error, 1 commented out your constructor and 2 uninstalling the package.

**Comment by JFossey** [comment]
So I tried to recreate this bug from a fresh project, and at first I struggled and wondered if it was something on my side. Eventually I figured it out.

The exception was only triggered once I added a `.md` file in a path needed to be processed.

**Comment by JFossey** [comment]
## package.json

``` json
{
  "name": "local-images",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/transformer-remark": "^0.6.4",
    "@gridsome/vue-remark": "^0.2.6",
    "gridsome": "^0.7.0",
    "gridsome-transformer-image": "^0.1.1"
  }
}
```

## config

**Note:** I experimented with using a vanilla markdown setup and with vue-remark to see if vue-remark was the trigger. It was not. `transformer-remark` + `gridsome-transformer-image` + a markdown file is the trigger.

``` js
module.exports = {
  siteName: 'Local images test',

  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'posts/**/*.md',
        typeName: 'Post',
        remark: {
          plugins: [
            // ...local plugins
          ]
        }
      }
    }
    // {
    //   use: '@gridsome/vue-remark',
    //   options: {
    //     typeName:   'Posts',
    //     pathPrefix: '/',
    //     baseDir:    './posts',
    //     index:      [ 'index', 'README' ],
    //     template:   './src/templates/Post.vue'
    //   }
    // }
  ]
}
```

## test.md

``` md
# Test

hello world
```

## Post.vue

``` vue
<template>
  <Layout>
    <VueRemarkContent />
  </Layout>
</template>
```

**Comment by JFossey** [comment]
## Reproduction Steps

Using the above file extracts as a reference the following steps reproduce the error.

1. `gridsome create local-images-test`
1. `cd local-images/`
1. `yarn add @gridsome/source-filesystem`
1. `yarn add @gridsome/transformer-remark`
1. `yarn add gridsome-transformer-image`
1. `mkdir posts`
1. `vi posts/test.md`
1. `vi src/templates/Post.vue`
1. `vi gridsome.config.js`
1. `gridsome build`

**Note:** If the `posts/` dir is empty and I dont create `test.md` there is no error.

**Comment by travis-r6s** [comment]
I think this is a bug, but just to note that this plugin is meant to be used if you are wanting to source images from a folder, and load them into GraphQL (so you have a collection of images) - is this what you were trying to do?

**Comment by JFossey** [comment]
> I think this is a bug, but just to note that this plugin is meant to be used if you are wanting to source images from a folder, and load them into GraphQL (so you have a collection of images) - is this what you were trying to do?

Yes, this is exactly my use case. One question - slightly off topic. with the images being loaded into graphql, does that mean we can using `<g-image>` - Context: https://github.com/gridsome/gridsome/issues/292

**Comment by travis-r6s** [comment]
Okay, got it - I'll take a look at this. And yes, it does mean that - as it is added to the store, Gridsome will process the images so you can use them with `<g-image>`.

**Comment by JFossey** [comment]
@thetre97 I think I have solved this. I traced the problem to the gray matter transformer that was trying to check the images for a YAML head and throwing an exception for anything that was not a string file content.

So based on this assumption I added checking to constructor hook for the mime type as it seems we hooking into all files regardless of mime type.

Using the below there seems to be no error. I still have to confirm if GraphQL is updated as expected, but I think this might work.

Thoughts?

``` js
class LocalImage {
  static mimeTypes () {
    return ['image/jpeg', 'image/png']
  }

  constructor(api, options) {
    options.assets.app.store.hooks.addNode.tap({
      name: 'LocalImage',
      before: 'TransformNodeContent'
    }, options => {
      // Return early skipping irrelevant mime types
      if (this.isAlledMimeType(options.internal) === false) {
        return;
      }

      // Hook into assets that are images
      options.internal.content = {
        ...options,
        internal: {},
        path: options.internal.origin
      }
    })
  }

  parse (source) {
    return {
      ...source,
      local: source.path
    }
  }

  isAlledMimeType(mimeType) {
    const allowedTypes = LocalImage.mimeTypes();
    return allowedTypes.indexOf(mimeType) !== -1;
  }
}

module.exports = LocalImage
```
